# Use the official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Set Python path to include the current directory
ENV PYTHONPATH="${PYTHONPATH}:/app"

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Expose the Flask default port
EXPOSE 5000

# Run the Flask app
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]